### PR TITLE
Update plugin.yml

### PR DESCRIPTION
**Pull request by Skull3x**
You left out bh :+1:

### CODE REVIEW

**Comment by TheKnightGamer** [comment]
Oh that why it was not working thanks.

**Comment by Taki21** [comment]
What is this? Math? Base Times Height? xD

**Comment by Skull3x** [comment]
Is it working for you now? Just to clarify if I actually helped

**Comment by TheKnightGamer** [comment]
Yeah but have some few bugs I will fix that.

**Comment by Skull3x** [comment]
Ok, I'm glad I helped

**Pull request merged**
